name: test_env_xmovie
channels:
  - conda-forge
dependencies:
  - xarray
  - dask
  - scipy
  - numpy
  - pytest
  - future
  - matplotlib
  - cartopy
  - pykdtree
  - opencv
  - pip:
    - codecov
    - pytest-cov
